# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "maven"
    directory: "/heatwave-core"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/heatwave-core"
    schedule:
      interval: "daily"
